apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  ports:
    - name: opensearch
      port: 80
      targetPort: 80
      protocol: TCP
    - name: another
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    app: opensearch
