apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db/service.yaml
  - db/deployment.yaml
  - opensearch/service.yaml
  - opensearch/deployment.yaml
  - cache-manager/service.yaml
  - cache-manager/deployment.yaml
  - db-syncer/service.yaml
  - db-syncer/deployment.yaml

configMapGenerator:
  - name: sql-setup
    files:
      - ./db/setup.sql
