apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-syncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-syncer
  template:
    metadata:
      labels:
        app: db-syncer
    spec:
      containers:
      - image: localhost:5000/db-syncer
        name: db-syncer
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: "http"
        env:
          - name: gingersnap.cache.uri
            value: hotrod://cache-manager
          - name: gingersnap.database.type
            value: MYSQL
          - name: gingersnap.database.host
            value: mysql
          - name: gingersnap.database.port
            value: '3306'
          - name: gingersnap.database.user
            value: gingersnap_user
          - name: gingersnap.database.password
            value: password
          - name: gingersnap.rule.us-east.connector.schema
            value: debezium
          - name: gingersnap.rule.us-east.connector.table
            value: customer
          - name: 'gingersnap.rule.us-east.value-columns'
            value: fullname,email
          - name: 'gingersnap.rule.us-east.key-columns'
            value: fullname
