apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cache-manager
  template:
    metadata:
      name: cache-manager
      labels:
        app: cache-manager
    spec:
      containers:
      - image: quay.io/gingersnap/cache-manager
        name: cache-manager
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
          - containerPort: 11222
        env:
          - name: quarkus.datasource.reactive.url
            value: mysql://mysql:3306/debezium
          - name: quarkus.elasticsearch.hosts
            value: opensearch:9200
          - name: quarkus.elasticsearch.username
            value: admin
          - name: quarkus.elasticsearch.password
            value: admin
          - name: service.index
            value: opensearch
